/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-06-14 05:22:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>ONLINE MOBILES</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/mobile.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/caroualresponsive.css\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\t\t <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write(" \r\n");
      out.write("  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("    <!-- Indicators -->\r\n");
      out.write("    <ol class=\"carousel-indicators\">\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"4\"></li>\r\n");
      out.write("      <li data-target=\"#myCarousel\" data-slide-to=\"5\"></li> \r\n");
      out.write("    </ol>\r\n");
      out.write("\r\n");
      out.write("    <!-- Wrapper for slides -->\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("  \r\n");
      out.write("      <div class=\"item active\">\r\n");
      out.write("       <a href=\"./resources/images/3.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/3.jpg\" alt=\"OPPO\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("          <h3>Redmi MAX-2</h3>\r\n");
      out.write("          <p>Even less!</p>        \r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("       <a href=\"./resources/images/5.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/5.jpg\" alt=\"VIVO\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("         <h3>iPhone-X</h3>\r\n");
      out.write("          <p>Say hello to the future!</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"item\">\r\n");
      out.write("       <a href=\"./resources/images/6.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/6.jpg\" alt=\"REDMI\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("        <h3>Google Pixel-2</h3>\r\n");
      out.write("          <p>Ask more of your phone!!!</p>  \r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("       <div class=\"item\">\r\n");
      out.write("        <a href=\"./resources/images/4.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/4.jpg\" alt=\"SAMSUNG\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("          <h3>Samsung Galaxy S8</h3>\r\n");
      out.write("          <p>The Next Big Things!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"item\">\r\n");
      out.write("    <a href=\"./resources/images/1.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/1.jpg\" alt=\"GIONEE\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("         <h3>Oppo</h3>\r\n");
      out.write("          <p>Selfie Expert!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"item\">\r\n");
      out.write("   <a href=\"./resources/images/2.jpg\" target=\"_blank\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/2.jpg\" alt=\"IPHONE\" style=\"width:100%;\">\r\n");
      out.write("        <div class=\"carousel-caption\">\r\n");
      out.write("          <h3>Vivo V7+</h3>\r\n");
      out.write("          <p>Perfect Shot- Perfect Selfie!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("  \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Left and right controls -->\r\n");
      out.write("    <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("      <span class=\"sr-only\">Next</span>\r\n");
      out.write("    </a>\r\n");
      out.write("  </div>\r\n");
      out.write("    <a href=\"ad\" target=\"_blank\">\r\n");
      out.write("          <img src=\"./resources/images/HDFC.gif\" alt=\"Sony\" style=\"width:100%\">\r\n");
      out.write("          </a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <div class=\"row\">\r\n");
      out.write("    <h3 class=\"modtitle\"><span> <font color=\"pink\"><b>New Arrivals!!!</b></font></span></h3>\r\n");
      out.write("  <div class=\"col-sm-3\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <a href=\"p1\" target=\"_blank\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/7.jpg\" alt=\"Lenovo\" style=\"width:100%\">\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("           <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/new.gif\" alt=\"Lenovo\" style=\"width:17%\">\r\n");
      out.write("           <strong>\r\n");
      out.write("            <p>Lenovo Z2 Plus Smartphone .</p>\r\n");
      out.write("            <p>Rs.9999/-</p> \r\n");
      out.write("            <p>FEATURES</p>\r\n");
      out.write("            <p>\r\n");
      out.write("Processor\t\r\n");
      out.write("Qualcomm Snapdragon 820, 64-Bit Custom Kryo Cores, Adreno 530\r\n");
      out.write("Operating System\t\r\n");
      out.write("Android 6.0.1\r\n");
      out.write("Memory\t\r\n");
      out.write("RAM: 4GB\r\n");
      out.write("ROM: 64GB\r\n");
      out.write("Battery\t\r\n");
      out.write("3500 mAh High Density (374 Wh/l) battery\r\n");
      out.write("  \r\n");
      out.write("            </p>\r\n");
      out.write("            </strong>         \r\n");
      out.write("            </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-3\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <a href=\"p2\" target=\"_blank\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mg.jpg\" alt=\"Motorola\" style=\"width:100%\">\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/sale.gif\" alt=\"Lenovo\" style=\"width:24%\">\r\n");
      out.write("          <strong>\r\n");
      out.write("            <p>Moto G4 Plus Smartphone .</p>\r\n");
      out.write("            <p>Rs.13999/-</p>\r\n");
      out.write("            <p>FEATURES</p>\r\n");
      out.write("            <p>\r\n");
      out.write("Processor\t\r\n");
      out.write("1.5 GHz Qualcomm Snapdragon 617 octa-core processor with 550 MHz Adreno 405 GPU\r\n");
      out.write("operating system\r\n");
      out.write("Android 6.0.1, Marshmallow\r\n");
      out.write("Memory\t\r\n");
      out.write("RAM: 2GB\r\n");
      out.write("ROM: 16GB\r\n");
      out.write("Battery\t\r\n");
      out.write("3000 mAh\r\n");
      out.write("  \r\n");
      out.write("            </p>\r\n");
      out.write("            </strong>         \r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-sm-3\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <a href=\"p3\" target=\"_blank\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/9.png\" alt=\"Sony\" style=\"width:100%\">\r\n");
      out.write("          <div class=\"caption\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/new.gif\" alt=\"Lenovo\" style=\"width:17%\">\r\n");
      out.write("          <strong>\r\n");
      out.write("            <p>Sony-Xperia XA Ultra Smartphone</p>\r\n");
      out.write("            <p>Rs.21999/-</p>\r\n");
      out.write("            <p>FEATURES</p>\r\n");
      out.write("            <p>\r\n");
      out.write("Processor\r\n");
      out.write("MediaTek MT6755 64 bit Octa Core processor\t\r\n");
      out.write("Operating System\t\r\n");
      out.write("Android 6.0.1 Marshmallow\r\n");
      out.write("Memory\t\r\n");
      out.write("RAM: 3GB\r\n");
      out.write("ROM: 16GB\r\n");
      out.write("Battery\t\r\n");
      out.write("2700 mAh\r\n");
      out.write("Display\r\n");
      out.write("15.2 cm Full HD curved display\r\n");
      out.write("Mobile \r\n");
      out.write("            </p>         \r\n");
      out.write("            </strong>\r\n");
      out.write("          </div>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div class=\"col-sm-3\">\r\n");
      out.write("      <div class=\"thumbnail\">\r\n");
      out.write("        <a href=\"redirect\" target=\"_blank\">\r\n");
      out.write("         <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/deals.png\" alt=\"Sony\" style=\"width:95%\">\r\n");
      out.write("         \r\n");
      out.write("         <a href=\"redirect\" target=\"_blank\">\r\n");
      out.write("         <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/save.gif\" alt=\"Sony\" style=\"width:47%\">\r\n");
      out.write("          \r\n");
      out.write("           <a href=\"redirect\" target=\"_blank\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/original.jpg\" alt=\"Sony\" style=\"width:76%\">\r\n");
      out.write("                 \r\n");
      out.write("        \r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" </div>\r\n");
      out.write("          \r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("   <h3 class=\"modtitle\"><span><font color=\"pink\"><b>Top Models</b></font></span></h3>\r\n");
      out.write("      <div id=\"adv_team_4_columns_carousel\" class=\"carousel slide four_shows_one_move team_columns_carousel_wrapper\" data-ride=\"carousel\" data-interval=\"2000\" data-pause=\"hover\">\r\n");
      out.write("         <!--========= Wrapper for slides =========-->\r\n");
      out.write("         <div class=\"carousel-inner\" role=\"listbox\">\r\n");
      out.write("            <!--========= 1st slide =========-->\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gn.jpg\" alt=\"slider 01\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Samsung</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-1\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ip8.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Iphone 8 Plus</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-2\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/la.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Lava</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-3\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mm.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Micromax</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--========= 2nd slide =========-->\r\n");
      out.write("            <div class=\"item active\">\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/t5.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Techmo</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-1\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/x1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Gionee</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-2\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/z1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Sony</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-3\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/gn.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>samsung</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--========= 3rd slide =========-->\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ip8.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>IPhone 8+</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-1\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/la.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Lava</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-2\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mm.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Micromax</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-3\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/t5.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Techmo</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           <!--========= 4th slide =========-->\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/x1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Gionee</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-1\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/z1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Sony</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-2\">\r\n");
      out.write("                  <img src=\"./resources/images/gn.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Samsung</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-3\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/ip8.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Iphone 8+</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--========= 5th Slide =========-->\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/la.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Lava</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-1\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/mm.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Micromax</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-2\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/x1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Gionee</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"col-xs-12 col-sm-6 col-md-3 team_columns_item_image cloneditem-3\">\r\n");
      out.write("                  <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/z1.jpg\" alt=\"slider 02\">\r\n");
      out.write("                  <div class=\"team_columns_item_caption\">\r\n");
      out.write("                     <h4>Sony</h4>\r\n");
      out.write("                     <hr>\r\n");
      out.write("                     <h5>Mobile</h5>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("             \r\n");
      out.write("     <a class=\"left carousel-control team_columns_carousel_control_left adv_left\" href=\"#adv_team_4_columns_carousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("         <span class=\"fa fa-angle-left team_columns_carousel_control_icons\" aria-hidden=\"true\"></span>\r\n");
      out.write("         <span class=\"sr-only\">Previous</span>\r\n");
      out.write("         </a>\r\n");
      out.write("         \r\n");
      out.write("         <a class=\"right carousel-control team_columns_carousel_control_right adv_right\" href=\"#adv_team_4_columns_carousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("         <span class=\"fa fa-angle-right team_columns_carousel_control_icons\" aria-hidden=\"true\"></span>\r\n");
      out.write("         <span class=\"sr-only\">Next</span>\r\n");
      out.write("         </a>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div > \r\n");
      out.write("\t\r\n");
      out.write("<div class=\"container-fluid page-builder-ltr\">\r\n");
      out.write("<div class=\"row row_tvsw row-style row-color\">\r\n");
      out.write("<div class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12 col_adt9 col-style\">\r\n");
      out.write("<div class=\"videos-grids\"><div class=\"module\">\r\n");
      out.write("<h3 class=\"modtitle\"><span><font color=\"pink\"><b>Videos</b></font></span></h3>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"services-inline\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<div class=\"policy1 col-lg-4 col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("<iframe width=\"370\" height=\"270\" frameborder=\"0\" allowfullscreen=\"\" src=\"https://www.youtube.com/embed/RKYjdTiMkXM\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"policy2 col-lg-4 col-md-4 col-sm-6 col-xs-12\">\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("<iframe width=\"370\" height=\"270\" frameborder=\"0\" allowfullscreen=\"\" src=\"https://www.youtube.com/embed/k0DN-BZrM4o\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"policy3 col-lg-4 col-md-4 col-sm-12 col-xs-12\">\r\n");
      out.write("<div class=\"inner\">\r\n");
      out.write("<iframe width=\"370\" height=\"270\" frameborder=\"0\" allowfullscreen=\"\" src=\"https://www.youtube.com/embed/8WLHsz7pyzA\"></iframe>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div></div>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
