/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-07-02 11:55:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<!-- \r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/mobile.css\"> -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./resources/css/reg.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Registration Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<br/>\r\n");
      out.write("\t<br/>\r\n");
      out.write("<img src=\"./resources/images/reg.jpg\" alt=\"Sony\" style=\"width:15%\">\t\r\n");
      out.write("\t<!-- <h3 class=\"modtitle\"><span><font color=\"green\">Registration Page</font></span></h3> -->\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t \r\n");
      out.write("\t<center>\r\n");
      out.write("\t<form action=\"registration\">\r\n");
      out.write("  <div class=\"containers\">\r\n");
      out.write("  <table>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><label><b><font color=\"blue\">UserId</font></b></label></td><td>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter UserID\" name=\"userId\" required class=\"form-control\" focus><td>\r\n");
      out.write("    </tr><tr>\r\n");
      out.write("     \r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Name</font></b></label></td><td>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Name\" name=\"name\" required class=\"form-control\"><td>\r\n");
      out.write("   </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Password</font></b></label></td><td>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Enter Password\" name=\"password\" required class=\"form-control\"><td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Repeat Password</font></b></label></td><td>\r\n");
      out.write("    <input type=\"password\" placeholder=\"Repeat Password\" name=\"psw-repeat\" required class=\"form-control\"><td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Age</font></b></label></td><td>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Age\" name=\"age\" required class=\"form-control\"><td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Gender</font></b></label></td><td>\r\n");
      out.write("    <input type=\"radio\" name=\"gender\" checked/>M<input type=\"radio\" name=\"gender\"/>F</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>\r\n");
      out.write("    <label><b><font color=\"blue\">Email</font></b></label></td><td>\r\n");
      out.write("    <input type=\"text\" placeholder=\"Enter Email\" name=\"email\" required class=\"form-control\"><td>\r\n");
      out.write("\t</tr>\r\n");
      out.write(" \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td><label><b><font color=\"blue\">Phone</font></b></label></td>\r\n");
      out.write("\t<td><input type=\"text\" placeholder=\"Enter Address\" name=\"phone\" required class=\"form-control\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td><label><b><font color=\"blue\">City</font></b></label></td>\r\n");
      out.write("\t<td><input type=\"text\" placeholder=\"Enter Address\" name=\"address\" required class=\"form-control\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t \r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("   </table>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("<br/>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"clearfix\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-success\"  data-toggle=\"tooltip\" data-placement=\"top\" title=\"Register Me!!!\"><i>Register Me!</i></button>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-danger\"  data-toggle=\"tooltip\" data-placement=\"top\" title=\"Cancel\">Cancel</button>\r\n");
      out.write("      <!-- <button type=\"button\" class=\"loginbtn\"  >Cancel</button>\r\n");
      out.write("      <button type=\"submit\" class=\"loginbtn\" >SignUp</button> -->\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("</center>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
